### ISSUE TITLE
Cell references in TrainingData.xlsx

### ISSUE THREAD

**Issue by ZenW00kie** [ewprodsec/hvss-calculator-lab#4]
I was looking at the training data file, and noticed that in the `Input` tab there are some incorrect cell references in XCIA. For example, Case ID 144 for XCIA score is looking at the match from Case ID 39, which means the XCIA score is 5 when it should be a 8.3 (at least from looking at the other rows that have same values for the XCIA parameters). I checked the other param scores, and that looks to be the only set of parameters with this.

**Comment by jacobbarkai** [comment]
Thanks for the feedback! Fixed accordingly.
